# Generated by Django 3.0.4 on 2020-04-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_table',
            name='salary',
            field=models.IntegerField(null=True),
        ),
    ]
